### ISSUE TITLE
Add settings and instruction to run Vagrant boxes (and its contents) behind proxy

### ISSUE THREAD

**Issue by jotamorais** [bogdanvlviv/i-vagrant#2]
Hi @bogdanvlviv. First of all, congrats for the pulling this together and sharing with the community.

This is not really an issue, but it would be great if we could have default settings and be able to switch proxy on and off when running behind corporate proxy. 
There are several steps that we need to go through when working behind proxy such as installing the vagrant-proxyconf plugin, add the config proxy properties for the image's network interfaces, push the proxy configuration into the machine instance so that it get applied as environment variables and then can be used in terminal and package managers (apt, curl, wget, git, etc, etc).

Do you think it's feasible or makes sense?

Let me know your thoughts.

Thank you!

**Comment by bogdanvlviv** [comment]
Hi @jotamorais. I can't answer your question because I'm not familiar with `vagrant-proxyconf`.
I think you can do it if it works as you wish.

Currently, I use this repo for my own needs (this saves me a lot of time):
 - Setting up everything I need on VM with Ubuntu
 - Setting up everything I need on my laptop with Ubuntu (after reinstalling this)
 - This repository even helps me to install some desktop apps like GIMP or Google Chrome because I need them too and don't want to spend my time every time (by doing the same things)after instalation of Ubuntu

The main slogan this repository is `"Try to fork this idea and build for own needs."`.

Thank you!
